[package]
name = "dlccryptlib"
version = "1.9.1"
edition = "2021"
description = "Library for working with DLC's with adaptor signatures (Discrete Log Contracts), by Cadena Bitcoin"
license = "MIT"

[lib]
name = "dlccryptlib"
# Dual crate type, cdylib needed for C-style linking
crate-type = ["cdylib", "rlib"]

[dependencies]
bip39 = "2.1.0"
bitcoin = "0.32.4"
secp256k1-sys = "0.10.1"
secp256k1-zkp = "0.11.0"

[features]
default = ["std"]
std = ["bitcoin/std", "secp256k1-zkp/rand-std"]
